CONTIKI_PROJECT = example-broadcast-leader-1 example-broadcast-leader-2 example-broadcast-leader-3
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
